### ISSUE TITLE
DISCUSSION/BUG: ClearLines will push the tiles to the direction of currentGravityDirection

### ISSUE THREAD

**Issue by karel-harjono** [karel-harjono/grav-shift-tetris#1]
Currently, ClearLines will push the tiles to the direction of currentGravityDirection. the issue is that all of the tiles on the board will be shifted to the direction of the gravity on Clear. This will leave gap at the other sides of the board.

how should we tackle this?

**Comment by jgresl** [comment]
Watch this video for an example

https://github.com/user-attachments/assets/edeac262-c4ea-4ba9-95f3-402ad0615674

**Comment by jgresl** [comment]
It seems here, that only the bottom half of the board shift down... and the existing tiles that are sitting on the halfway line seem to grow or expand.

This might be unintended but a very good existing solution. What is the alternative? To create gaps? having the tiles grow will increase the chances of epic combos.... where perhaps all 4 edges clear at the same time.

Given how difficult this game is already, it might be a good idea to leave this feature as is... at least for now.

**Comment by jgresl** [comment]
I think I recorded this video after the issue was already fixed / addressed?

In this commit
https://github.com/karel-harjono/grav-shift-tetris/commit/21efac26f633ac1f833e4214fcf783d29215d809

**Comment by karel-harjono** [comment]
sorry, I did not see this message. I tried to fix it but it did not cover all test case(honestly still buggy)
